#!/bin/sh

if [ $# -ne 3 ]
then
echo "Requires three  arguments:"
echo "file-output.mov file-source.mov file-new-output.mov"
exit -1
fi

ffmpeg -y -i $1 -i $2 -c copy -map 0:v:0 -map 1:a:0? -shortest $3
